server:
  port: 8201
spring:
  application:
    name: mall-gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
    registry-fetch-interval-seconds: 10
zuul:
  sensitive-headers:  #默认会过滤Cookie,Set-Cookie,Authorization，配置为空不过滤
  add-host-header: true #设置为true重定向是会添加host请求头
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
