spring:
  profiles:
    active: dev #默认为开发环境
  application:
    name: mall-search

server:
  port: 8081

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

logging:
  level:
    root: info
    com.macro.mall: debug



